# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8349b0006cfaa8871bc7e331ec7e4741130aac319303a84984823a55ac4c3cf1debd5cde473a4f398d4f95fde8e7fae953166bd0c82d0e4c61d583aba57dbdc

test:
  secret_key_base: bbd83319f5c77ae8814eba64c048273fe1b473bfb5b96f0e94045fd8de4da94e5e2c8c6d51e4ab752cedd1bfd7bb6d0b0ce3c029bbcffe6fa1273622810355ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
